# Generated by Django 4.2.13 on 2024-06-23 12:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='feature_image',
            field=cloudinary.models.CloudinaryField(default='default_profile_shke8m', max_length=255, verbose_name='image'),
        ),
    ]
