# Generated by Django 4.2.13 on 2024-07-20 17:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='default_profile_viridian', max_length=255, verbose_name='image'),
        ),
    ]
