# Generated by Django 4.2.13 on 2024-06-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_feature_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='feature_image',
            new_name='profile_image',
        ),
    ]
