# Generated by Django 4.2.13 on 2024-06-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artpieces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('liked_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artpieces.artpiece')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
