# Generated by Django 4.2.13 on 2024-06-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artpieces', '0003_alter_artpiece_art_medium'),
        ('likes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artpieces.artpiece'),
        ),
    ]
