# Generated by Django 4.2.13 on 2024-07-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artpieces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_message', models.CharField(max_length=255)),
                ('response_message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Declined')], default=0)),
                ('buyer_has_checked', models.BooleanField(default=True)),
                ('artist_has_checked', models.BooleanField(default=False)),
                ('artpiece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artpieces.artpiece')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
