# Generated by Django 4.2.13 on 2024-07-03 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artpieces', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='artpiece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artpieces.artpiece'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
