# Generated by Django 4.2.13 on 2024-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_alter_enquiry_artpiece_alter_enquiry_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='buyer_has_checked',
            field=models.BooleanField(default=True),
        ),
    ]
