# Generated by Django 4.2.13 on 2024-06-23 14:53

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('art_collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(180)])),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('art_medium', models.IntegerField(choices=[(0, 'No medium selected'), (1, 'Oil'), (2, 'Watercolour'), (3, 'Gouache'), (4, 'Acrylic'), (5, 'Charcoal'), (6, 'Chalk'), (7, 'Photography'), (8, 'Mixed media'), (9, 'Other')], default=0)),
                ('for_sale', models.IntegerField(choices=[(0, 'Not for sale'), (1, 'For sale'), (2, 'Sold')], default=0)),
                ('art_collection_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_collection', to='art_collections.artcollection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
