# Generated by Django 4.2.13 on 2024-06-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpieces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='artpiece',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='hashed_artpieces', to='artpieces.hashtag'),
        ),
    ]
