# Generated by Django 4.2.13 on 2024-06-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpieces', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='art_medium',
            field=models.CharField(choices=[('noselection', 'No medium selected'), ('oil', 'Oil'), ('watercolour', 'Watercolour'), ('gouache', 'Gouache'), ('acrylic', 'Acrylic'), ('charcoal', 'Charcoal'), ('chalk', 'Chalk'), ('photography', 'Photography'), ('mixedmedia', 'Mixed media'), ('other', 'Other')], default=0, max_length=30),
        ),
    ]
