# Generated by Django 4.2.13 on 2024-06-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_collections', '0002_initial'),
        ('artpieces', '0003_alter_artpiece_art_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpiece',
            name='art_collection_id',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='art_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_artpieces', to='art_collections.artcollection'),
        ),
    ]
